config/routes.rb
#rake routes in Gitbash to see the URL pattern

Rails.application.routes.draw do


devise_for :users, :controllers => { sessions: 'sessions' , registrations: 'registrations'}
devise_scope :user do
  #root to: "devise/sessions#new"
  root to: "posts#index"

get '/login' => 'admin/sessions#new'
get '/logout' => 'admin/sessions#destroy'
get 'users/:id' => 'users#show'

  namespace :admin do

    resources :posts
    resources :users, only: [:index, :destroy]
    resources :settings, only: [:new, :create, :edit, :update]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages
    resources :visitors, only: [:index, :destroy]
    resources :comments, only:[:index, :update, :destroy]
    resources :tags
    resources :sessions, only: [:new, :create, :destroy]
    #to restrict from deletein admin , you specify only v
    resources :administrators, only: [:index, :edit, :update]
    resources :diarylogs, only: [:index, :show, :edit, :update]
  end

  
  resources :messages
  resources :settings 
  resources :users, only: [:index, :show]
  resources :diarylogs 
  resources :help
  resources :fitabout
   resources :previewdiary
  resources :posts do
  resources :comments 
  end
  resources :comments 
  end
  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
	has_secure_password

	has_many :posts

	validates :fullname, presence: true
	validates :username, presence: true, format: {with: /@/, message: 'is not a valid. Please enter a valid email address.'}
	validates :password, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
  belongs_to :visitor

  has_many :notifications, as: :notifiable, dependent: :destroy

 def self.matching_fullname_or_message params
 	joins(:visitor).where("fullname LIKE ? OR message LIKE ?", "%#{params}%", "%#{params}%")
end
end

app/models/diarylog.rb
class Diarylog < ActiveRecord::Base
  belongs_to :user

#I want to validate my posts so that the title & content field must be filed before submission.
  validates :date, presence: true
  validates :time, presence: true
  validates :meal_type, presence: true
  validates :description, presence: true
  


  #Validates date can only be on ore before this date. 

 validates_date :date, :on_or_before => lambda { Date.current }

end

app/models/message.rb
class Message < ActiveRecord::Base
validates :content, presence: true
validates :subject, presence: true


belongs_to :visitor
belongs_to :user
  def self.matching_fullname_or_content params
  	joins(:visitor).where("fullname LIKE ? OR content LIKE ?", "%#{params}%", "%#{params}%")
	end

def mark_read
	update(status: true)if status == false
end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base

 
 has_attached_file :image, styles: {medium: "500x500"}
 validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	# When I delete the post it needs to delete in databse (post_tags) to avoid redundant data.
	has_many :comments, dependent: :destroy
	has_many :post_tags, dependent: :destroy
	has_many :tags, through: :post_tags
  belongs_to :administrator
  belongs_to :user

#I want to validate my posts so that the title & content field must be filed before submission.
  validates :title, presence: true
  validates :content, presence: true
  validates :publish, presence: true


  def self.matching_title_or_content search
  	where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
  end

  def self.filter_by_tags param_tag
    includes(:tags).where(publish: true, tags: {name: param_tag}).order(id: :desc)
    
  end
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ActiveRecord::Base
	def self.site_name
	 Setting.first.try(:site_name)
	end

	def self.post_per_page
	Setting.first.try(:post_per_page)
end

	def self.tag_visibile?
	Setting.first.try(:tag_visibility)
end
end

app/models/tag.rb
#Checking if a particlar id exisists in it
class Tag < ActiveRecord::Base
	has_many :posts, through: :post_tags
	validates :name, presence: true


	def in_use?
	PostTag.exists?(tag_id: self.id)
	end
end

app/models/user.rb
class User < ActiveRecord::Base

has_attached_file :image, styles: {medium: "300x300", thumb: "150x150#"}
 validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :notifications, as: :notifiable, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :messages, dependent: :destroy

#A user has many diarylogs
has_many :diarylogs
#I want to validate my posts so that the title & content field must be filed before submission.
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_format_of :first_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
  validates_format_of :last_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
end

app/models/visitor.rb
#When we delete visitor , make sure it deletes all their comments
class Visitor < ActiveRecord::Base
	has_many :notifications, as: :notifiable, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :messages, dependent: :destroy

end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < Admin::ApplicationController
	def index
		@administrators = Administrator.all
end

def edit
	@administrator = Administrator.find(params[:id])
end

def update
@administrator = Administrator.find(params[:id])

if @administrator.update(administrator_params)
	flash[:notice] = "Administrator was successfully updated"
	redirect_to admin_administrators_url
else
	flash[:alert] = "There was a problem updating the administrator. Please try again."
	render 'edit'
end
end

private

def administrator_params
	params.require(:administrator).permit(:id, :fullname, :username, :password)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#When you are in a ruby file you dont need the tags '<% %>'
	#Helper methods help to speed things up & removes repetition
	#Could be in views/admin but this enables a tidy code / easy to read

	#Default truth is Active. Default falsey is Pending 
	#Otherwise.status_converter(status, truthy:nil, falsey:nil)
	#and do it manuallly for the others.
	def status_converter(status, truthy:'Active', falsey: 'Pending')
	if status
	truthy
else
	falsey
end
end
#time_ago_in_words(@post.created_at) .. making it into a helper so I dont have to keep repeating myself
def time_ago time
	"#{time_ago_in_words(time)} ago"
end

def double_digit_number n
	'%02d' % n
end 
end

def current_administrator
		@administrator ||= Administrator.find(session[:current_administrator_id]) if session[:current_administrator_id]
	end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diarylogs_helper.rb
module DiarylogsHelper
end

app/helpers/fitabout_helper.rb
module FitaboutHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/administrators/edit.html.erb

<head> 
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>

<h4><%= link_to 'Back', admin_administrators_path %> |</h4>

<div class="container">
    <h1>Administrators</h1> 
    <hr></h3>

<p><%= render 'validation_errors', object: @administrator %></p>

<%= bootstrap_form_for [:admin, @administrator] do |f| %>

<div class="col-md-2 personal-info">
<div class ="container">
 <div class="field input-group col-lg-7 col-lg-offset-2">
     <div class="input-group-addon">Full Name</div>
		<%= f.text_field :fullname, autofocus: true, hide_label: true  %> 
      
       
</div>

  <br>  <br>
<div class="col-md-2 personal-info">
<div class ="container">
 <div class="field input-group col-lg-7 col-lg-offset-2">
     <div class="input-group-addon">Username</div>
		<%= f.text_field :username, hide_label: true  %> 
       
       

</div>

 <br> <br>
<div class="col-md-2 personal-info">
<div class ="container">
 <div class="field input-group col-lg-7 col-lg-offset-2">
     <div class="input-group-addon">Change Password</div>
		<%= f.password_field :password, autofocus: true, hide_label: true  %> 

</div>
 <br> <br>
<div class ="container">
<div class="form-group">
        <div class="col-lg-9 col-lg-offset-5">
            <button type="submit" class="btn btn-primary">Update</button>
              </div>
    </div>
</p>

<% end %>

app/views/admin/administrators/index.html.erb

<head> 
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>

</style>
<div class="container">
    <h1>All Administrators</h1> 
    <hr></h3>

<br></br>
<table class="table table=bordered table hover">
	<thread>
		<tr>
			<th>Fullname</th>
			<th>Username</th>
			<th>Created</th>
			<th>Actions</th>
		</tr>
	</thread>
	<tbody>
		<% @administrators.each do |administrator| %>
			<tr>
				<td><%= administrator.fullname %></td>
				<td><%= administrator.username %></td>
				<td><%= time_ago(administrator.created_at) %></td>
				<td>
					<%= link_to 'Edit', edit_admin_administrator_path(administrator) %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

</div>
<br><br><br>