config/routes.rb
#rake routes in Gitbash to see the URL pattern

Rails.application.routes.draw do


devise_for :users, :controllers => { sessions: 'sessions' , registrations: 'registrations'}
devise_scope :user do
  #root to: "devise/sessions#new"
  root to: "posts#index"

get '/login' => 'admin/sessions#new'
get '/logout' => 'admin/sessions#destroy'
get 'users/:id' => 'users#show'

  namespace :admin do

    resources :posts
    resources :users, only: [:index, :destroy]
    resources :settings, only: [:new, :create, :edit, :update]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages
    resources :visitors, only: [:index, :destroy]
    resources :comments, only:[:index, :update, :destroy]
    resources :tags
    resources :sessions, only: [:new, :create, :destroy]
    #to restrict from deletein admin , you specify only v
    resources :administrators, only: [:index, :edit, :update]
    resources :diarylogs, only: [:index, :show, :edit, :update]
  end

  
  resources :messages
  resources :settings 
  resources :users, only: [:index, :show]
  resources :diarylogs 
  resources :help
  resources :fitabout
   resources :previewdiary
  resources :posts do
  resources :comments 
  end
  resources :comments 
  end
  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
end

app/models/diarylog.rb
class Diarylog < ActiveRecord::Base
  belongs_to :user

#I want to validate my posts so that the title & content field must be filed before submission.
  validates :date, presence: true
  validates :time, presence: true
  validates :meal_type, presence: true
  validates :description, presence: true
  


  #Validates date can only be on ore before this date. 

 validates_date :date, :on_or_before => lambda { Date.current }

end

app/controllers/admin/diarylogs_controller.rb
class Admin::DiarylogsController < Admin::ApplicationController

	def index

params[:search].present?
 	@diarylogs = Diarylog.where('user_id LIKE ?', "%#{params[:search]}%").page params[:page]
 else
 #get all the logs from the databse and display in the diarylog instance variable.
		@diarylogs = Diarylog.all.order(id: :desc).page params[:page]
end
#end

	def new
end

	def create
end

	def edit
		 @diarylog = Diarylog.find(params[:id])
end

    def update
    	     	@diarylog = Diarylog.find(params[:id])
    	if @diarylog.update(diarylog_params)
    		redirect_to admin_diarylogs_path, notice: "diary log was succefully updated"
    		else 
			flash[:alert]= 'There was a problem with the update'
			render :edit
		end
end

def show
	@diarylog = Diarylog.find(params[:id])
	
end

def destroy
	@diarylog = Diarylog.find(params[:id])
	@diarylog.destroy

	redirect_to :back, notice: "The log has been deleted"
end 
private
def diarylog_params
	params.require(:diarylog).permit(:id, :meal_type, :description, :calories, :sugar, :fat, :sodium, :sat_fat, :fiber, :date, :time, :user_id, :carbs, :protein, :feedback)

end
end

app/controllers/diarylogs_controller.rb
class DiarylogsController < ApplicationController


#get all the logs from the databse and display in the diarylog instance variable.

	def index
		#if 
		#params[:search].present?
 #	@diarylogs = Diarylog.where('diarylogs.user_ID LIKE ?', "%#{params[:search]}%").page params[:page]
 #get all the logs from the databse and display in the diarylog instance variable.
		@diarylogs = Diarylog.all.order(id: :desc).page params[:page]
end
			
	def new
	@diarylog = Diarylog.new
end



	def create
		@diarylog = Diarylog.new(diarylog_params)
		@diarylog.user_id = current_user.id

		if @diarylog.save
			redirect_to diarylogs_url, notice: "diary log was saved"
		else 
			flash[:alert]= 'There was a problem'
			render :new
		end
end

	def edit
		@diarylog = Diarylog.find(params[:id])
end 

    def update
    	@diarylog = Diarylog.find(params[:id])
    	if @diarylog.update(diarylog_params)
    		redirect_to diarylog_path, notice: "diary log was succefully updated"
    		else 
			flash[:alert]= 'There was a problem with the update'
			render :edit
		end
end

def show
	@diarylog = Diarylog.find(params[:id])
end

def destroy
	@diarylog = Diarylog.find(params[:id])
	@diarylog.destroy

	redirect_to :back, notice: "The log has been deleted"
end 

private
def diarylog_params
	params.require(:diarylog).permit(:id, :meal_type, :description, :calories, :sugar, :fat, :sodium, :sat_fat, :fiber, :date, :time, :user_id, :carbs, :protein, :feedback)

end
end

app/helpers/diarylogs_helper.rb
module DiarylogsHelper
end

app/views/admin/diarylogs/_form.html.erb
<%=  render 'validation_errors', object: @diarylog %>

<%= bootstrap_form_for [@diarylog] do |f| %>


  <h4><%= link_to 'Back', admin_diarylogs_path %> |</h4>

<div class="container">
    <h1> <%= @diarylog.user.first_name%> 's Food Log | <small> <%= @diarylog.date %> at
      <%=  @diarylog.time.strftime("%H:%M") %></small> 

     <hr></h1>

    <br>
<p><h4 class = "text-left"><b>Type of Meal</b>: <%= @diarylog.meal_type %></h4><p>
  <br>
<p><h4 class = "text-left"><b>Description</b>: <%= @diarylog.description %></h4><p> 
   <br>
   <h4 class = "text-center"><p><b>Calories</b>:<%= @diarylog.calories %><p>
<p><b>Sugar</b>:<%= @diarylog.sugar %><p>
<p><b>Fat</b>:<%= @diarylog.fat %><p>
<p><b>Carbs</b>:<%= @diarylog.carbs %><p>
<p><b>Protein</b>:<%= @diarylog.protein %><p>
<p><b>Sodium</b>:<%= @diarylog.sodium %><p>
<p><b>Sat Fat</b>:<%= @diarylog.sat_fat %><p>
<p><b>Fiber</b>:<%= @diarylog.fiber %><p></h4>
<hr>
 <div class="form-group">
  <br>
  <br>
        <div class="row">
            <div class="col-xs-9 col-lg-offset-2">
                <label class="control-label">Feedback (Short term goal) </label>
           <%= f.text_area :feedback, rows:5, hide_label: true,autofocus: true, placeholder: 'Leave suitable advice and add a short term goal for individual here. '  %>
            </div>
            <br>
            <% end %>
  <br> 
 </div>    
 <div class ="container">
  <div class="actions col-lg-5 col-lg-offset-4">
     <button type="submit" class=" col-lg-12 btn btn-primary">Update Diarylog</button>
        </div>


<br><br><br><br><br>
<br>



app/views/admin/diarylogs/edit.html.erb
<head> 
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>
<%= render 'form'%>

app/views/admin/diarylogs/index.html.erb
<head> 
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>

<div class="container">
    <h1> All Diarylogs</h1> 
    <hr></h3>

<div class = "jumbotron text-center">
  <h2><b>Monitor progress and identify areas that need attention or improvement!  </b>
  	<p>
  	</h2>

</div>

<div class = "container">
<h4><div class="text-center"><%= paginate @diarylogs %></div></h4>


<table class="table table=bordered table hover">
	<thread>
		<tr>
			<th>Date Created</th>
			<th>Name</th>
			<th>Location</th>
			<th>Actions</th>
		</tr>
	</thread>
	<tbody>

		<% @diarylogs.each do |diarylog| %>
			<tr>
				<td><%= diarylog.created_at.strftime("%D") %></td>
				<td><%= diarylog.user.first_name + ' ' + diarylog.user.last_name %></td>
				<td><%= diarylog.user.location %></td>
				<td>
					<%= link_to 'Give Feedback', edit_admin_diarylog_path(diarylog) %> | 
					<%= link_to 'View', admin_diarylog_path(diarylog) %> |
					<%= link_to 'Delete', diarylog_path(diarylog), method: :delete, data: {confirm:  'Are you sure you would like to delete this log?'}  %> 
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

	



app/views/admin/diarylogs/show.html.erb


<head> 
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>


<h4><%= link_to 'Back', admin_diarylogs_path %> |</h4>

<div class="container">
    <h1> <%= @diarylog.user.first_name%> 's Food Log | <small> <%= @diarylog.date %> at
      <%=  @diarylog.time.strftime("%H:%M") %></small> 

     <hr></h1>

    <br>
<p><h4 class = "text-left"><b>Type of Meal</b>: <%= @diarylog.meal_type %></h4><p>
  <br>
<p><h4 class = "text-left"><b>Description</b>: <%= @diarylog.description %></h4><p> 
   <br>
   <h4 class = "text-center"><p><b>Calories</b>:<%= @diarylog.calories %><p>
<p><b>Sugar</b>:<%= @diarylog.sugar %><p>
<p><b>Fat</b>:<%= @diarylog.fat %><p>
<p><b>Carbs</b>:<%= @diarylog.carbs %><p>
<p><b>Protein</b>:<%= @diarylog.protein %><p>
<p><b>Sodium</b>:<%= @diarylog.sodium %><p>
<p><b>Sat Fat</b>:<%= @diarylog.sat_fat %><p>
<p><b>Fiber</b>:<%= @diarylog.fiber %><p></h4>
<hr>

 <p><h4 class = "text-left"><b>Feedback (Short-term Goal)</b>: <%= @diarylog.feedback %> <p></h4>

<br><br><br><br><br><br>






