config/routes.rb
#rake routes in Gitbash to see the URL pattern

Rails.application.routes.draw do


devise_for :users, :controllers => { sessions: 'sessions' , registrations: 'registrations'}
devise_scope :user do
  #root to: "devise/sessions#new"
  root to: "posts#index"

get '/login' => 'admin/sessions#new'
get '/logout' => 'admin/sessions#destroy'
get 'users/:id' => 'users#show'

  namespace :admin do

    resources :posts
    resources :users, only: [:index, :destroy]
    resources :settings, only: [:new, :create, :edit, :update]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages
    resources :visitors, only: [:index, :destroy]
    resources :comments, only:[:index, :update, :destroy]
    resources :tags
    resources :sessions, only: [:new, :create, :destroy]
    #to restrict from deletein admin , you specify only v
    resources :administrators, only: [:index, :edit, :update]
    resources :diarylogs, only: [:index, :show, :edit, :update]
  end

  
  resources :messages
  resources :settings 
  resources :users, only: [:index, :show]
  resources :diarylogs 
  resources :help
  resources :fitabout
   resources :previewdiary
  resources :posts do
  resources :comments 
  end
  resources :comments 
  end
  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
	has_secure_password

	has_many :posts

	validates :fullname, presence: true
	validates :username, presence: true, format: {with: /@/, message: 'is not a valid. Please enter a valid email address.'}
	validates :password, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
  belongs_to :visitor

  has_many :notifications, as: :notifiable, dependent: :destroy

 def self.matching_fullname_or_message params
 	joins(:visitor).where("fullname LIKE ? OR message LIKE ?", "%#{params}%", "%#{params}%")
end
end

app/models/diarylog.rb
class Diarylog < ActiveRecord::Base
  belongs_to :user

#I want to validate my posts so that the title & content field must be filed before submission.
  validates :date, presence: true
  validates :time, presence: true
  validates :meal_type, presence: true
  validates :description, presence: true
  


  #Validates date can only be on ore before this date. 

 validates_date :date, :on_or_before => lambda { Date.current }

end

app/models/message.rb
class Message < ActiveRecord::Base
validates :content, presence: true
validates :subject, presence: true


belongs_to :visitor
belongs_to :user
  def self.matching_fullname_or_content params
  	joins(:visitor).where("fullname LIKE ? OR content LIKE ?", "%#{params}%", "%#{params}%")
	end

def mark_read
	update(status: true)if status == false
end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base

 
 has_attached_file :image, styles: {medium: "500x500"}
 validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	# When I delete the post it needs to delete in databse (post_tags) to avoid redundant data.
	has_many :comments, dependent: :destroy
	has_many :post_tags, dependent: :destroy
	has_many :tags, through: :post_tags
  belongs_to :administrator
  belongs_to :user

#I want to validate my posts so that the title & content field must be filed before submission.
  validates :title, presence: true
  validates :content, presence: true
  validates :publish, presence: true


  def self.matching_title_or_content search
  	where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
  end

  def self.filter_by_tags param_tag
    includes(:tags).where(publish: true, tags: {name: param_tag}).order(id: :desc)
    
  end
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ActiveRecord::Base
	def self.site_name
	 Setting.first.try(:site_name)
	end

	def self.post_per_page
	Setting.first.try(:post_per_page)
end

	def self.tag_visibile?
	Setting.first.try(:tag_visibility)
end
end

app/models/tag.rb
#Checking if a particlar id exisists in it
class Tag < ActiveRecord::Base
	has_many :posts, through: :post_tags
	validates :name, presence: true


	def in_use?
	PostTag.exists?(tag_id: self.id)
	end
end

app/models/user.rb
class User < ActiveRecord::Base

has_attached_file :image, styles: {medium: "300x300", thumb: "150x150#"}
 validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :notifications, as: :notifiable, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :messages, dependent: :destroy

#A user has many diarylogs
has_many :diarylogs
#I want to validate my posts so that the title & content field must be filed before submission.
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_format_of :first_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
  validates_format_of :last_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
end

app/models/visitor.rb
#When we delete visitor , make sure it deletes all their comments
class Visitor < ActiveRecord::Base
	has_many :notifications, as: :notifiable, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :messages, dependent: :destroy

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController


def index
  	@users = User.order(id: :desc).page(params[:page]).first 3
  	@posts = Post.order(id: :desc).page(params[:page]).first 3
  	@diarylogs = Diarylog.order(id: :desc).page(params[:page]).first 3
  	@messages = Message.order(id: :desc).page(params[:page]).first 3
  	@comments = Comment.page(params[:page]).last 2
  
  	@visitors = Visitor.last 5
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diarylogs_helper.rb
module DiarylogsHelper
end

app/helpers/fitabout_helper.rb
module FitaboutHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/index.html.erb
<head> 
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>


<div class="container">
<div class = "jumbotron text-center">
  <h1><b>Dashboard</b>

  	  	</h1>
  	  </div>

<div class="btn-group btn-group-justified">
                        <a href="http://localhost:3000/admin/administrators" class="btn btn-primary col-sm-3">
                            <i class="glyphicon glyphicon-plus"></i>
                            <br>Administrators
                        </a>
                        <a href="http://localhost:3000/admin/users" class="btn btn-primary col-sm-3">
                            <i class="glyphicon glyphicon-cloud"></i>
                            <br> Users
                        </a>
                        <a href="http://localhost:3000/admin/diarylogs" class="btn btn-primary col-sm-3">
                            <i class="glyphicon glyphicon-envelope"></i>
                            <br> Diary Logs
                        </a>
                        <a href="http://localhost:3000/admin/posts" class="btn btn-primary col-sm-3">
                            <i class="glyphicon glyphicon-pencil"></i>
                            <br> Posts
                        </a>
                        <a href="http://localhost:3000/admin/tags" class="btn btn-primary col-sm-3">
                  #
                            <br> Tags
                        </a>
                        <a href="http://localhost:3000/admin/messages" class="btn btn-primary col-sm-3">
                            <i class="glyphicon glyphicon-envelope"></i>
                            <br> Messages
                        </a>
                        </div>
<br>
<hr>
  <div class="row">
                <!-- center left-->
                <div class="col-md-6">
                    
                     <div class="panel">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class="active"><a href="#profile" data-toggle="tab"><h4>System Updates</h4></a></li>
                            <li><a href="#messages" data-toggle="tab"><h4> Inbox Messages</h4></a></li>
                            <li><a href="#settings" data-toggle="tab"><h4> Comments</h4></a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="profile">
                            	<br>
                               <p></p> The databse is currently set to hold up to <u><b>2000</b></u> users. This can be changed to hold values as large as 32767. See  <a href = "http://www.sqlite.org/limits.html"> Limits In SQLite </a> for more information. 
                   <br>  <br>
                        <p>   <h3><small> Current amount of users: 130 </small></h3>
                        	 <div class="progress">
                                <div class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="100" style="width: 5%">
                                    <span class="sr-only">5% Complete</span>

                            </div> 
                                </div><br><br>                            </div>
                            <div class="tab-pane fade in " id="messages">
                               <table class="table table=bordered table hover">
	<thread>
		<tr>
			<th><h5  class = "text-left"><b>Date Sent</b></h5></th>
			<th><h5  class = "text-left"><b>Message ID</b></h5></th>
			<th><h5  class = "text-left"><b>Subject </b></h5></th>
			<th><h5  class = "text-left"><b>Actions</b></h5></th>
		</tr>
	</thread>
	<tbody>

		<% @messages.each do |message| %>
		
 					<tr>
				<td><h5 class = "text-left"> <%=  message.created_at.strftime("%D") %></h5></td>
				<td><h5 class = "text-left"> <%=  message.id %></h5></td>
				<td><h5 class = "text-left"> <%=  message.subject %></h5></td>
					<td>
			
					<%= link_to 'View', message_path(message) %> |
					<%= link_to 'Del', message_path(message), method: :delete, data: {confirm: 'Are you sure you want to delete this message?'} %> 
					
				
					

				</td>
			</tr>
		<% end %>
	</tbody>
</table>
                            </div>
                            <div class="tab-pane fade in " id="settings">
                                

<% @comments.each do |comment| %>
<h5 class = "text-center"><p>
<b><%= comment.user.first_name %> </b> posted message on <b>'<%= comment.post.title %>'</b> <smal> about <%= time_ago comment.post.created_at %></small></p>
<p><%= comment.message %></p>
<p><%= link_to 'Delete', admin_comment_path(comment), method: :delete, data: {confirm: 'Are you sure you would like to delete this comment ?'} %></p></h5>

<hr>
<% end %>



                            </div>
                        </div>

                    </div>


             
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h4>Users</h4></div>
                        <div class="panel-body">
                           
                           
<table class="table table=bordered table hover">
	<thread>
		<tr>
			<th>Name</th>
			<th>Location</th>
			<th>Signed Up</th>
			<th>Login Count </th>
			
		</tr>
	</thread>
	<tbody>
	<% @users.each do |user| %>
			<tr>
				<td><%= link_to user.first_name + ' ' + user.last_name, user %></td>
				<td><%= user.location %></td>
				<td><%= time_ago(user.created_at) %></td>
				<td><%= user.sign_in_count %></td>
					
				
			</tr>
		<% end %>
	</tbody>
</table> 

<a href = 'http://localhost:3000/admin/users' class =  "btn btn-default col-lg-offset-5 text-right  "> View All </a>
                           
                        </div>
                        <!--/panel-body-->
                    </div>
                    <!--/panel-->

                    <hr>
<br>
             
                   
                    <!--/tabs-->

                    <hr>
                 
                </div>
                <!--/col-->
                <div class="col-md-6">




                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <h4>Recent Posts</h4>
                         </div>
                        <div class="panel-body">
                        
                           
                      

<table class="table table=bordered table hover">
	<thread>
		<tr>
			<th>Title</th>
			<th>Comments</th>
			<th>Posted</th>
			<th>Actions</th>
		</tr>
	</thread>
	<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td><%= truncate(post.title, length: 35, seperator: '') %></td>
				<td><%= post.comments.count %></td>
				<td><%= time_ago post.created_at %></td>
				<td>
					<%= link_to 'edit', edit_admin_post_path(post) %>
					<%= link_to 'view', admin_post_path(post) %>
					<%= link_to 'del', admin_post_path(post), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'} %> 
				</td>						
			</tr>
		<% end %>
	</tbody>
</table>

                              <a href = 'http://localhost:3000/admin/posts/new' class =  "btn btn-primary col-lg-offset-4 text-right"> Create New </a>
							
							<a href = 'http://localhost:3000/admin/posts' class =  "btn btn-default col-lg-offset-0 text-right  "> View All </a>
                        </div>
                    </div>
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h4>Recent Diary Logs</h4></div>
                        <div class="panel-body">
                           <table class="table table=bordered table hover"> 
                            <thread>
		<tr>
			<th>Date Created</th>
			<th>Name</th>
			<th>Location</th>
			<th>Actions</th>
		</tr>
	</thread>
	<tbody>

		<% @diarylogs.each do |diarylog| %>
			<tr>
				<td><%= diarylog.created_at.strftime("%D") %></td>
				<td><%= diarylog.user.first_name + ' ' + diarylog.user.last_name %></td>
				<td><%= diarylog.user.location %></td>
				<td>
					
					<%= link_to 'view', admin_diarylog_path(diarylog) %> 
					<%= link_to 'delete', diarylog_path(diarylog), method: :delete, data: {confirm:  'Are you sure you would like to delete this log?'}  %> 
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<a href = 'http://localhost:3000/admin/diarylogs' class =  "btn btn-default col-lg-offset-5 text-right  "> View All </a>
                        

                  	</div>
                    </div>
               
                