config/routes.rb
#rake routes in Gitbash to see the URL pattern

Rails.application.routes.draw do


devise_for :users, :controllers => { sessions: 'sessions' , registrations: 'registrations'}
devise_scope :user do
  #root to: "devise/sessions#new"
  root to: "posts#index"

get '/login' => 'admin/sessions#new'
get '/logout' => 'admin/sessions#destroy'
get 'users/:id' => 'users#show'

  namespace :admin do

    resources :posts
    resources :users, only: [:index, :destroy]
    resources :settings, only: [:new, :create, :edit, :update]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages
    resources :visitors, only: [:index, :destroy]
    resources :comments, only:[:index, :update, :destroy]
    resources :tags
    resources :sessions, only: [:new, :create, :destroy]
    #to restrict from deletein admin , you specify only v
    resources :administrators, only: [:index, :edit, :update]
    resources :diarylogs, only: [:index, :show, :edit, :update]
  end

  
  resources :messages
  resources :settings 
  resources :users, only: [:index, :show]
  resources :diarylogs 
  resources :help
  resources :fitabout
   resources :previewdiary
  resources :posts do
  resources :comments 
  end
  resources :comments 
  end
  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
end

app/models/diarylog.rb
class Diarylog < ActiveRecord::Base
  belongs_to :user

#I want to validate my posts so that the title & content field must be filed before submission.
  validates :date, presence: true
  validates :time, presence: true
  validates :meal_type, presence: true
  validates :description, presence: true
  


  #Validates date can only be on ore before this date. 

 validates_date :date, :on_or_before => lambda { Date.current }

end

app/controllers/admin/diarylogs_controller.rb
class Admin::DiarylogsController < Admin::ApplicationController

	def index

params[:search].present?
 	@diarylogs = Diarylog.where('user_id LIKE ?', "%#{params[:search]}%").page params[:page]
 else
 #get all the logs from the databse and display in the diarylog instance variable.
		@diarylogs = Diarylog.all.order(id: :desc).page params[:page]
end
#end

	def new
end

	def create
end

	def edit
		 @diarylog = Diarylog.find(params[:id])
end

    def update
    	     	@diarylog = Diarylog.find(params[:id])
    	if @diarylog.update(diarylog_params)
    		redirect_to admin_diarylogs_path, notice: "diary log was succefully updated"
    		else 
			flash[:alert]= 'There was a problem with the update'
			render :edit
		end
end

def show
	@diarylog = Diarylog.find(params[:id])
	
end

def destroy
	@diarylog = Diarylog.find(params[:id])
	@diarylog.destroy

	redirect_to :back, notice: "The log has been deleted"
end 
private
def diarylog_params
	params.require(:diarylog).permit(:id, :meal_type, :description, :calories, :sugar, :fat, :sodium, :sat_fat, :fiber, :date, :time, :user_id, :carbs, :protein, :feedback)

end
end

app/controllers/diarylogs_controller.rb
class DiarylogsController < ApplicationController


#get all the logs from the databse and display in the diarylog instance variable.

	def index
		#if 
		#params[:search].present?
 #	@diarylogs = Diarylog.where('diarylogs.user_ID LIKE ?', "%#{params[:search]}%").page params[:page]
 #get all the logs from the databse and display in the diarylog instance variable.
		@diarylogs = Diarylog.all.order(id: :desc).page params[:page]
end
			
	def new
	@diarylog = Diarylog.new
end



	def create
		@diarylog = Diarylog.new(diarylog_params)
		@diarylog.user_id = current_user.id

		if @diarylog.save
			redirect_to diarylogs_url, notice: "diary log was saved"
		else 
			flash[:alert]= 'There was a problem'
			render :new
		end
end

	def edit
		@diarylog = Diarylog.find(params[:id])
end 

    def update
    	@diarylog = Diarylog.find(params[:id])
    	if @diarylog.update(diarylog_params)
    		redirect_to diarylog_path, notice: "diary log was succefully updated"
    		else 
			flash[:alert]= 'There was a problem with the update'
			render :edit
		end
end

def show
	@diarylog = Diarylog.find(params[:id])
end

def destroy
	@diarylog = Diarylog.find(params[:id])
	@diarylog.destroy

	redirect_to :back, notice: "The log has been deleted"
end 

private
def diarylog_params
	params.require(:diarylog).permit(:id, :meal_type, :description, :calories, :sugar, :fat, :sodium, :sat_fat, :fiber, :date, :time, :user_id, :carbs, :protein, :feedback)

end
end

app/helpers/diarylogs_helper.rb
module DiarylogsHelper
end

app/views/diarylogs/_form.html.erb
<%=  render 'validation_errors', object: @diarylog %>

<%= bootstrap_form_for [@diarylog] do |f| %>


  
<hr>
<br>


    <div class="form-group">
        <div class="row">
            <div class="col-xs-3 col-lg-offset-3">
                <label class="control-label"><h4>Meal Type</h4></label>
         <%= f.text_field :meal_type,  hide_label: true, placeholder: "Breakfast, Lunch, Dinner or Snack "%>
            </div>

            <div class="col-xs-2 ">
                <label class="control-label"><h4>Date of Meal</h4></label>
               <%= f.date_field :date, hide_label: true  %>
            </div>

            <div class="col-xs-2">
                <label class="control-label"><h4>Time Eaten</h4></label>
              	<%= f.time_field :time, hide_label: true %>
            </div>
        </div>
         <div class="col-xs-7 col-lg-offset-8"> <h4><small> <b>&nbsp;&nbsp;Note:</b> 24 Hour Clock </small></h4></div>

    <div class="form-group">
        <div class="row">
            <div class="col-xs-7 col-lg-offset-3">
                <label class="control-label"><h4>Description</h4></label>
           <%= f.text_area :description, rows:7, :maxlength => 600, hide_label: true, placeholder: 'How did you cook this? Was this shop bought?'  %>
            </div>     
 </div>
 <div class="col-xs-7 col-lg-offset-3"> <h4><small> Describe the meal in <b> 600 </b> characters or less.</small></h4></div>
</div>
</div>
<hr>
<h3 class = "text-center"> Please Enter the Amount for the Following: </h3>
<div class = "alert alert-info text-center"> <h4 class = "text center"><b>H E L P </b></h4> 
  <p><h5> 1. The amount of nutrients and calories contained in a product can normally be found on the back of the product, under the <b>nutrition label.</b> <a href = "#example" data-toggle="modal" class =  "btn-xs btn-info"> View Example </a> </p></h5> 
  2.  If there is more than one product, enter the total amount in the appropriate box below.
<br><br>
 <h4><small> If you are having trouble with the form and unable to enter the correct data, please make a note of this in the <b>Description Box</b> above. </h4></small></h4>
</div>
				

 <div class="form-group">
        <div class="row">
            <div class="col-xs-1 col-lg-offset-2">
                <label class="control-label">Calories</label>
             		<%= number_field_tag :calories, nil, min: 0, max: 2500, hide_label: true  %>
            </div>

            <div class="col-xs-1 ">
                <label class="control-label">Sugar</label>
               <%= number_field_tag :sugar, nil, min: 0, max: 1000, hide_label: true  %>
            </div>

            <div class="col-xs-1">
                <label class="control-label">Fat</label>
              <%= number_field_tag :fat, nil, min: 0, max: 1000, hide_label: true  %>
            </div>
            <div class="col-xs-1">
                <label class="control-label">Carbs</label>
              <%= number_field_tag :carbs, nil, min: 0, max: 1000, hide_label: true  %>
            </div>
            <div class="col-xs-1">
                <label class="control-label">Protein</label>
              <%= number_field_tag :protein, nil, min: 0, max: 1000, hide_label: true  %>
            </div>
         
            <div class="col-xs-1">
                <label class="control-label">Sodium</label>
              	<%= number_field_tag :sodium, nil, min: 0, max: 1000, hide_label: true, placeholder: 'OPT.' %>
            </div>
            <div class="col-xs-1">
                <label class="control-label">Sat Fat</label>
              	<%= number_field_tag :sat_fat, nil, min: 0, max: 1000, hide_label: true, placeholder: 'OPT.' %>
            </div>
   <div class="col-xs-1">
                <label class="control-label">Fiber</label>
           <%= number_field_tag :fiber, nil, min: 0, max: 1000, hide_label: true, placeholder: 'OPT.' %>
            </div>
          </div>
            <br>

    <div class"col-xs-1 col-lg-offset-6">
<p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
      <a href = "#more" data-toggle="modal" > Why do i need to provide this information? Learn more... </a></li></p>
</div>



<div class="modal fade" id="more" data-backdrop="false" role = "dialog">
<div class = "modal-dialog">
  <div class = "modal-content">
    <div class = "modal-header">
     </div>
    <div class = "modal-body">
    <p>
    Whilst some of the fields are optional, it is recommended that you enter as much information as you can to ensure you get the most out of your food diary. This data will help the fitness instructor to diagnose your nutrition intake and offer suitable advice.

    <p> For more information on balanced diets visit: <a href = "http://www.nhs.uk/Livewell/Goodfood/Pages/eatwell-plate.aspx 
"> The NHS Eatwell Plate </a>

     <p> We strongly reccommend you enter the correct details. <u> Honesty is the best policy. </u><p>
  </div>
    <div class = "modal-footer">
      <a class = "btn btn-primary" data-dismiss = "modal" >OK</a>
     </div>
</div>
  </div>
        </div>

        <div class="modal fade" id="example" data-backdrop="false" role = "dialog">
<div class = "modal-dialog">
  <div class = "modal-content">
    <div class = "modal-header">
     </div>
    <div class = "modal-body">
<%= image_tag("Nutrition.png", :alt => "ATFT") %>
  </div>
    <div class = "modal-footer">
      <a class = "btn btn-primary" data-dismiss = "modal" >OK</a>
     </div>
</div>
  </div>
        </div>
        <br>
<br>
<hr>
<% if user_signed_in? %> 
<div class ="container">
  <div class="actions col-lg-4 col-lg-offset-4">
     <button type="submit" class=" col-lg-12 btn btn-primary">Submit Diarylog</button>
        </div>

 </div>




<div class="form-group">
	<br>
	<br>
        <div class="row">
            <div class="col-xs-7 col-lg-offset-3">
                <label class="control-label">Feedback (Short term goal) </label>
           <%= f.text_area :feedback, rows:5, hide_label: true, placeholder: 'Please leave this blank. This is for your fitness instructor to complete.'  %>
            </div>
 </div>
 <% else %>

<div class ="container">
  <div class="actions col-lg-4 col-lg-offset-4">
      <p><a href = "#contact" data-toggle="modal" class =  "col-lg-12 btn btn-primary"> Submit Diarylog </a></li></p>
        </div>

 </div>

<div class="form-group">
	<br>
	<br>
        <div class="row">
            <div class="col-xs-7 col-lg-offset-3">
                <label class="control-label">Feedback (Short term goal) </label>
           <%= f.text_area :feedback, rows:5, hide_label: true, placeholder: 'Please leave this blank. You will recieve a response within 24 hours.'  %>
            </div>
 </div>
<br><br><br><br><br><br><br><br><br><br>
 <div class="modal fade" id="contact" data-backdrop="false" role = "dialog">
<div class = "modal-dialog">
  <div class = "modal-content">
    <div class = "modal-header">
      <h3><b>Attention!</b></h3>
    </div>
    <div class = "modal-body">
    <p>
     


<h4>This is a preview. You need to <b>sign in</b> or <b>sign up</b> before continuing.</h4>


</p>








  </div>
    <div class = "modal-footer">
      <a href = 'http://localhost:3000/users/sign_up' class =  "btn btn-primary">OK</a>
      <a class = "btn btn-danger" data-dismiss = "modal" >Cancel</a>
  </div>
</div>
  </div>
 <%end %>


<% end %>
<br><br><br><br><br><br><br><br><br><br>

app/views/diarylogs/edit.html.erb
<h1>Editing Diary Log</h1>
<head> 
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>
<%= render 'form'%>

app/views/diarylogs/index.html.erb

<head> 
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

</style>
<div class="container">
    <h1> Food Diary Logs</h1> 
    <hr></h3>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= image_tag("diary.png", :alt => "Fitnessclass feed") %> 



 <a href = 'http://localhost:3000/diarylogs/new' class =  "btn btn-primary text-center  "> Create New Log</a>

<br><br>
<table class="table table=bordered table hover">
	<thread>
		<tr>
			<th><h5  class = "text-left"><b>Date Created</b></h5></th>
			<th><h5  class = "text-left"><b>Time Eaten </b></h5></th>
			<th><h5  class = "text-left"><b>Type of Meal </b></h5></th>
			<th><h5  class = "text-left"><b>Actions</b></h5></th>
		</tr>
	</thread>
	<tbody>

		<% @diarylogs.each do |diarylog| %>
			<% if user_signed_in?%>
 			<% if diarylog.user_id == current_user.id %>
			<tr>
				<td><h5 class = "text-left"> <%=  diarylog.date %></h5></td>
				<td><h5 class = "text-left"> <%=  diarylog.time.strftime("%H:%M") %></h5></td>
				<td><h5 class = "text-left"> <%= diarylog.meal_type %></h5></td>
				<td>
			
					<%= link_to 'View', diarylog_path(diarylog) %> |
					<%= link_to 'Edit', edit_diarylog_path(diarylog) %> | 
					<%= link_to 'Del', diarylog_path(diarylog), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'} %> 
						<% end %>
					<% end %>
					

				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<p>
<div class = "container">
<h4><div class="text-center"><%= paginate @diarylogs %></div></h4>
<br> <br><br> <br><br> <br>

app/views/diarylogs/new.html.erb
<head> 
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>

<% if user_signed_in? %>
<h4><%= link_to 'Back', diarylogs_path %> | </h4>
<% else %>
<h4><%= link_to 'Back', root_path %> | </h4>
<% end %>

<div class="container">
    <h1> Food Diary</h1> 
    <hr></h3>

<br>
<div class ="container">
 
<h1 class = "text-center"> What Did I Eat Today ?</h1>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= image_tag("balanced-diet.jpg", :alt => "diet") %>

<% if user_signed_in? %>

<p><h4> The food diary highlights the different types of food that make up our diet, and we show you the proportions you should eat them in to have a healthy, balanced diet. We advise you to input as much information as you can as this will help us to diagnose your nutrition intake. If you provide us with enough information we can guide you with short-term goals.
	<br>
<p> Help us to help you, Anytime is FitTime.</p></h4> 
<% else %>
	<p><h4> The food diary highlights the different types of food that make up our diet, and we show you the proportions you should eat them in to have a healthy, balanced diet. We advise you to input as much information as you can as this will help us to diagnose your nutrition intake. If you provide us with enough information we can guide you with short-term goals. </p>
<br>
	<p>Help us to help you, Anytime is FitTime. </p> </h4>
		<% end %>




<%= render 'form' %>


</div>

app/views/diarylogs/show.html.erb


<head> 
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>
<% if user_signed_in? %>
<h4><%= link_to 'Back', diarylogs_path %> | </h4>
<% else %>
<h4><%= link_to 'Back', root_path %> | </h4>
<% end %>

<div class="container">
    <h1> <%= @diarylog.user.first_name%> 's Food Log | <small> <%= @diarylog.date %> at
      <%=  @diarylog.time.strftime("%H:%M") %></small> 

    <a href = "#contact" data-toggle="modal" class =  "col-lg-offset-5 text-right btn btn-success"> TIP </a>

    <hr></h1>

  



  <br>
<p><h4 class = "text-left"><b>Type of Meal</b>: <%= @diarylog.meal_type %></h4><p>
  <br>
<p><h4 class = "text-left"><b>Description</b>: <%= @diarylog.description %></h4><p> 
   <br>
   <hr>
 <p><h4 class = "text-left"><b>Feedback (Short-term Goal)</b>: <%= @diarylog.feedback %> <p></h4>
 <hr>

<div class = "alert alert-info text-center"><h3><b>G U I D E L I N E</b><p></h3>

 <h5 class= "text-left"> Whilst the pie chart on the left represents your overall nutrition intake, the <b>Eatwell</b> pie chart on the right shows you how much of what you eat, should come from each food group. To help you get the right balance of the main food groups, take a look at the <b> Eatwell </b> pie chart and use it as a guide to maintain a healthy diet.  </p>

 <p> It's important to have only small amounts of foods high in fat and/or sugar. Eating a healthy, balanced diet is an important part of maintaining good health, and can help you feel your best. </b> </h5>



<h3 class= "text-center"> <small><p> Learn more about balanced diets on the <a href = "http://www.nhs.uk/Livewell/Goodfood/Pages/eight-tips-healthy-eating.aspx
"> <u>The NHS Livewell </u></a> page and read about the energy contained in food. </small></h3>
</div>    
  

        </div>      
    <style>
    body { background:#; }
  </style>

<% if @diarylog.meal_type == 'Snack' %>

  <div class="container text-center col-lg-4 col-lg-offset-1">
<h1>Your Snack</h1>
<div id="graph"></div>
  <script>
Morris.Donut({
  element: 'graph',
data: [
    {label: "Calories", value: 450},
    {label: "Sugar", value: 228},
     {label: "Fat", value: 25},
     {label: "Carbs", value: 143},
    {label: "Protein", value: 10},
     {label: "Sodium", value: 0},
     {label: "Fiber", value: 0},
    {label: "Saturated Fat", value: 0}
  ],
  backgroundColor: '#000000',
  labelColor: '#5316FA',
  colors: [
    '#D22118',
    '#F6FA16',
    '#67C69D',
    '#5316FA',
    '#FA9316',
    '#FC1A92',
    '#C22FF3',
    '#A46230'

  ],

});</script>


</div>

<div class="container col-lg-6">
  <h1 class="text-center">Eatwell Snack </h1>

<div id= "example"></div>
<script>
Morris.Donut({
  element: 'example',
  data: [
    {label: "Calories", value: 250},
    {label: "Sugar", value: 40},
     {label: "Fat", value: 5},
     {label: "Carbs", value: 100},
    {label: "Protein", value: 20},
     {label: "Sodium", value: 20},
     {label: "Fiber", value: 50},
    {label: "Saturated Fat", value: 5}
  ],
   backgroundColor: '#000000',
  labelColor: '#060',
  colors: [
   '#D22118',
    '#F6FA16',
    '#67C69D',
    '#5316FA',
    '#FA9316',
    '#FC1A92',
    '#C22FF3',
    '#A46230'
  ],
});</script>

<% end %>

<% if @diarylog.meal_type == 'Dinner' %>

  <div class="container text-center col-lg-4 col-lg-offset-1">
<h1>Your Dinner</h1>
<div id="graph"></div>
  <script>
Morris.Donut({
  element: 'graph',
data: [
    {label: "Calories", value: 450},
    {label: "Sugar", value: 95 },
     {label: "Fat", value: 325},
     {label: "Carbs", value: 750},
    {label: "Protein", value: 50},
     {label: "Sodium", value: 0},
     {label: "Fiber", value: 35},
    {label: "Saturated Fat", value: 0}
  ],
  backgroundColor: '#000000',
  labelColor: '#D22118',
  colors: [
    '#D22118',
    '#F6FA16',
    '#67C69D',
    '#5316FA',
    '#FA9316',
 '#FC1A92',
    '#C22FF3',
    '#A46230'


  ],

});</script>


</div>

<div class="container col-lg-6">
  <h1 class="text-center">Eatwell Dinner </h1>

<div id= "example"></div>
<script>
Morris.Donut({
  element: 'example',
  data: [
    {label: "Calories", value: 450},
    {label: "Sugar", value: 60},
     {label: "Fat", value: 150},
     {label: "Carbs", value: 350},
    {label: "Protein", value: 75},
     {label: "Sodium", value: 30},
     {label: "Fiber", value: 100},
    {label: "Saturated Fat", value: 20}
  ],
backgroundColor: '#000000',
  labelColor: '#D22118',
  colors: [
    '#D22118',
    '#F6FA16',
    '#67C69D',
    '#5316FA',
    '#FA9316',
   '#FC1A92',
    '#C22FF3',
    '#A46230'

  ],
});</script>


<% end %>


<% if @diarylog.meal_type == 'Breakfast' %>

  <div class="container text-center col-lg-4 col-lg-offset-1">
<h1>Your Breakfast</h1>
<div id="graph"></div>
  <script>
Morris.Donut({
  element: 'graph',
data: [
    {label: "Calories", value: 650},
    {label: "Sugar", value: 78},
     {label: "Fat", value: 5},
     {label: "Carbs", value: 143},
    {label: "Protein", value: 10},
     {label: "Sodium", value: 0},
     {label: "Fiber", value: 0},
    {label: "Saturated Fat", value: 0}
  ],
  backgroundColor: '#000000',
  labelColor: '#5316FA',
  colors: [
    '#D22118',
    '#F6FA16',
    '#67C69D',
    '#5316FA',
    '#FA9316',
   '#FC1A92',
    '#C22FF3',
    '#A46230'


  ],

});</script>


</div>

<div class="container col-lg-6">
  <h1 class="text-center">Eatwell Snack </h1>

<div id= "example"></div>
<script>
Morris.Donut({
  element: 'example',
  data: [
    {label: "Calories", value: 250},
    {label: "Sugar", value: 40},
     {label: "Fat", value: 5},
     {label: "Carbs", value: 100},
    {label: "Protein", value: 20},
     {label: "Sodium", value: 0},
     {label: "Fiber", value: 0},
    {label: "Saturated Fat", value: 0}
  ],
   backgroundColor: '#000000',
  labelColor: '#060',
  colors: [
   '#D22118',
    '#F6FA16',
    '#67C69D',
    '#5316FA',
    '#FA9316',
 '#FC1A92',
    '#C22FF3',
    '#A46230'

  ],
});</script>

<% end %>





<div class="modal fade" id="contact" data-backdrop="false" role = "dialog">
<div class = "modal-dialog model-success">
  <div class = "modal-content model-success">
    <div class = "modal-header model-success">
      <h3>Eight Tips for Healthy Eating</h3>
    </div>
    <div class = "modal-body">
    
<p>1. Eat lots of fruit and veg.</p>
<p>2. Base your meals on starchy foods.</p>
<p>3. Eat more fish. </p>
<p>4. Cut down on saturated fat and sugar.</p>
<p>5. Eat less salt.</p>
<p>6. Get Active.</p>
<p>7. Drink about 1.6 to 2 litres of water everyday.</p>
<p>8. Dont skip breakfast.</p>
<br>
 <p> For more information visit: <a href = "http://www.nhs.uk/Livewell/Goodfood/Pages/eight-tips-healthy-eating.aspx"> The NHS Healthy Eating</a>

  </div>
    <div class = "modal-footer">
      <a class = "btn btn-primary" data-dismiss = "modal" >OK</a>
   
  </div>
</div>
  </div>
    </div>

<a href = "#more" data-toggle="modal" > <h4 class = "text-right"> What does this mean ?</h4></a>


</div>
</div>

<div class="container text-center col-lg-offset-1"><%= image_tag("Legend.png", :alt => "ATFT") %></div>
<br><br><br> <br><br><br>   <br>
</div>



<div class="modal fade" id="more" data-backdrop="false" role = "dialog">
<div class = "modal-dialog">
  <div class = "modal-content">
    <div class = "modal-header">
     </div>
    <div class = "modal-body">
    <p>
    <b>Have You Read The Guideline Presented ? </b> 

   <p> If you have any further questions or any suggestions about the Food Diary facility, drop us a message on our Contact Page. 
</p> </h5>
   <a href = 'http://localhost:3000/messages' class =  "btn btn-default "> Contact Us Now</a>
   <br>
   <br>
    <div class = "modal-footer">
      <a class = "btn btn-primary" data-dismiss = "modal" >OK</a>
     </div>
</div>
  </div>
        </div>



   	





